In [1]:
# 创建一个示例列表
import os

my_list = [1, 2, 3, 4, 5]

# 使用 pop() 方法删除并返回最后一个元素
removed_element = my_list.pop()
my_list.append(7)

# 打印删除的元素和更新后的列表
print("Removed element:", removed_element)
print("Updated list:", my_list)


Removed element: 5
Updated list: [1, 2, 3, 4, 7]


In [2]:
import torch
import torch.nn as nn
import copy

# 定义一个简单的模块
class SimpleModule(nn.Module):
    def __init__(self):
        super(SimpleModule, self).__init__()
        self.linear = nn.Linear(10, 10)

# 创建一个包含N个相同模块的ModuleList
N = 3
module = SimpleModule()
module_list = nn.ModuleList([copy.deepcopy(module) for i in range(N)])

# 打印模块列表
print(module_list)


ModuleList(
  (0): SimpleModule(
    (linear): Linear(in_features=10, out_features=10, bias=True)
  )
  (1): SimpleModule(
    (linear): Linear(in_features=10, out_features=10, bias=True)
  )
  (2): SimpleModule(
    (linear): Linear(in_features=10, out_features=10, bias=True)
  )
)


In [3]:
import torch
import torch.nn as nn

class SimpleModule(nn.Module):
    def __init__(self):
        super(SimpleModule, self).__init__()
        self.linear = nn.MultiheadAttention(40, 4, dropout=0.1)

    def forward(self, x):
        return self.linear(x)

# 创建模块实例
module = SimpleModule()

# 获取模块中需要优化的参数
parameters = list(module.parameters())
print("Number of parameters:", len(parameters))

# 打印每个参数的形状
for name, param in module.named_parameters():
    print(f"Parameter name: {name}, Shape: {param.shape}")

Number of parameters: 4
Parameter name: linear.in_proj_weight, Shape: torch.Size([120, 40])
Parameter name: linear.in_proj_bias, Shape: torch.Size([120])
Parameter name: linear.out_proj.weight, Shape: torch.Size([40, 40])
Parameter name: linear.out_proj.bias, Shape: torch.Size([40])


In [4]:
import torch
import torch.nn as nn
from torchviz import make_dot

# 创建输入示例
input_q = torch.randn(10, 20, 40)
input_k = torch.randn(10, 20, 40)
input_v = torch.randn(10, 20, 40)

# 创建 MultiheadAttention 模块
multihead_attention = nn.MultiheadAttention(40, 4, dropout=0.1)

# 使用 make_dot 输出计算图
output, _ = multihead_attention(input_q, input_k, input_v)
print(output.shape)


torch.Size([10, 20, 40])


In [5]:
import torch
import torch.nn as nn

# 创建一个示例全零张量
zero_tensor = torch.zeros(3, 3)

# 打印原始全零张量
print("Zero tensor:")
print(zero_tensor)

# 使用 nn.LayerNorm 进行归一化
layer_norm = nn.LayerNorm(normalized_shape=zero_tensor.size()[1:])
normalized_tensor = layer_norm(zero_tensor)

# 打印归一化后的张量
print("Normalized tensor:")
print(normalized_tensor)

Zero tensor:
tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])
Normalized tensor:
tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]], grad_fn=<NativeLayerNormBackward0>)


In [6]:
import torch
import torch.nn as nn

class MyModel(nn.Module):
    def __init__(self):
        super(MyModel, self).__init__()
        self.linear_layer = nn.Linear(in_features=10, out_features=5)

    def forward(self, x):
        output = self.linear_layer(x)
        return output

# 创建模型实例
model = MyModel()

# 创建一个全零的输入张量
input_tensor = torch.zeros(3, 10)

# 进行前向传播
output = model(input_tensor)
print(output)

tensor([[ 0.1992, -0.1266, -0.0129,  0.0329, -0.0862],
        [ 0.1992, -0.1266, -0.0129,  0.0329, -0.0862],
        [ 0.1992, -0.1266, -0.0129,  0.0329, -0.0862]],
       grad_fn=<AddmmBackward0>)


In [7]:
import torch

# 创建示例张量
tensor1 = torch.tensor([1, 2, 3])
tensor2 = torch.tensor([4, 5, 6])
tensor3 = torch.tensor([7, 8, 9])

# 将张量堆叠成新的张量
stacked_tensor = torch.stack([tensor1, tensor2, tensor3])

print("Stacked tensor:")
print(stacked_tensor)
print("Shape:", stacked_tensor[0])


Stacked tensor:
tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])
Shape: tensor([1, 2, 3])


In [8]:
type2class = {
            "cabinet": 0,
            "bed": 1,
            "chair": 2,
            "sofa": 3,
            "table": 4,
            "door": 5,
            "window": 6,
            "bookshelf": 7,
            "picture": 8,
            "counter": 9,
            "desk": 10,
            "curtain": 11,
            "refrigerator": 12,
            "showercurtrain": 13,
            "toilet": 14,
            "sink": 15,
            "bathtub": 16,
            "garbagebin": 17,
        }
class2type = {type2class[t]: t for t in type2class}

In [9]:
for t in type2class:
    print(t)

cabinet
bed
chair
sofa
table
door
window
bookshelf
picture
counter
desk
curtain
refrigerator
showercurtrain
toilet
sink
bathtub
garbagebin


In [10]:
import numpy as np
nyu40ids = np.array(
            [3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 14, 16, 24, 28, 33, 34, 36, 39]
        )
nyu40id2class = {
    nyu40id: i for i, nyu40id in enumerate(list(nyu40ids))
}

In [11]:
nyu40id2class

{3: 0,
 4: 1,
 5: 2,
 6: 3,
 7: 4,
 8: 5,
 9: 6,
 10: 7,
 11: 8,
 12: 9,
 14: 10,
 16: 11,
 24: 12,
 28: 13,
 33: 14,
 34: 15,
 36: 16,
 39: 17}

In [2]:
import argparse
from utils import config
def make_args_parser():
    parser = argparse.ArgumentParser("Wireframe Reconstruction Using Transformers", add_help=False)

    # Config
    parser.add_argument('--config', default='./config/config/WFTR.yaml', type=str, help='config file')

    # Training
    parser.add_argument("--start_epoch", default=-1, type=int)
    parser.add_argument("--max_epoch", default=720, type=int)
    parser.add_argument("--eval_every_epoch", default=10, type=int)
    parser.add_argument("--seed", default=0, type=int)

    # Testing
    parser.add_argument("--test_only", default=False, action="store_true")
    parser.add_argument("--test_ckpt", default=None, type=str)

    # I/O
    parser.add_argument("--checkpoint_dir", default=None, type=str)
    parser.add_argument("--log_every", default=10, type=int)
    parser.add_argument("--log_metrics_every", default=20, type=int)
    parser.add_argument("--save_separate_checkpoint_every_epoch", default=100, type=int)

    # Distributed Training
    parser.add_argument("--ngpus", default=1, type=int)
    parser.add_argument("--dist_url", default="tcp://localhost:12345", type=str)
    args = parser.parse_args()

    assert args.config is not None
    cfg = config.load_yaml_config(args.config)
    args = config.merge_args_cfg(args, cfg)
    return args


In [3]:
make_args_parser()

usage: Wireframe Reconstruction Using Transformers [--config CONFIG]
                                                   [--start_epoch START_EPOCH]
                                                   [--max_epoch MAX_EPOCH]
                                                   [--eval_every_epoch EVAL_EVERY_EPOCH]
                                                   [--seed SEED] [--test_only]
                                                   [--test_ckpt TEST_CKPT]
                                                   [--checkpoint_dir CHECKPOINT_DIR]
                                                   [--log_every LOG_EVERY]
                                                   [--log_metrics_every LOG_METRICS_EVERY]
                                                   [--save_separate_checkpoint_every_epoch SAVE_SEPARATE_CHECKPOINT_EVERY_EPOCH]
                                                   [--ngpus NGPUS]
                                                   [--dist_url DIST_URL]
Wireframe Reco

SystemExit: 2

C:\ProgramData\anaconda3\lib\site-packages\IPython\core\interactiveshell.py:3468: UserWarning: To exit: use 'exit', 'quit', or Ctrl-D.
  warn("To exit: use 'exit', 'quit', or Ctrl-D.", stacklevel=1)


In [12]:
print("-"*35, 'Done !!!', "-"*35)

----------------------------------- Done !!! -----------------------------------


In [13]:
from torch.utils.tensorboard import SummaryWriter
writer = SummaryWriter("ZCH_Tensorboard_Trying_logs")      #第一个参数指明 writer 把summary内容 写在哪个目录下

for i in range(100):
    writer.add_scalar("y=x",i,i)

for i in range(100):
    writer.add_scalar("y=2*x",2*i,i)


writer.close()     #将event log写完之后，记得close()

ModuleNotFoundError: No module named 'tensorboard'

In [1]:
from datetime import datetime
time_str = datetime.now()
time_str = time_str.strftime('%d-%m-%Y-%Hh-%Mm-%Ss')

In [2]:
print(time_str)

22-08-2023-14h-09m-46s


In [ ]:
import numpy as np

# 已知信息
center_point = np.array([1.0, 2.0, 3.0])
direction_vector = np.array([0.5, 0.5, 0.5])  # 方向向量可以是单位向量或非单位向量
segment_length = 2.0

# 计算半段长度
half_segment_length = segment_length / 2

# 计算线段的两个端点
endpoint1 = center_point - half_segment_length * direction_vector
endpoint2 = center_point + half_segment_length * direction_vector

print("Endpoint 1:", endpoint1)
print("Endpoint 2:", endpoint2)


In [3]:
import torch

# 创建两个示例张量
x = torch.tensor([[1.0, 2.0], [3.0, 4.0]])
y = torch.tensor([[5.0, 6.0], [7.0, 8.0]])

# 计算两个张量之间的欧氏距离
distances = torch.cdist(x, y)

print(distances)

tensor([[5.6569, 8.4853],
        [2.8284, 5.6569]])


In [19]:
import torch

def torch2D_Hausdorff_distance(x,y): # Input be like (Batch,width,height)
    distance_matrix = torch.cdist(x,y,p=2) # p=2 means Euclidean Distance
    distance_matrix = distance_matrix.view(2, 256, 29, 30, -1)

    value1 = distance_matrix.min(-1)[0].max(-1, keepdim=True)[0]
    value2 = distance_matrix.min(-2)[0].max(-1, keepdim=True)[0]

    value = torch.cat((value1, value2), dim=-1)

    return value.max(-1)[0]

if __name__ == "__main__":
    u = torch.rand( 2,256 * 30, 3)

    v = torch.rand( 2, 29 * 30, 3)

    print("Input shape is (B,W,H):", u.shape, v.shape)
    HD = torch2D_Hausdorff_distance(u,v)
    print("Hausdorff Distance is:", HD.shape)

Input shape is (B,W,H): torch.Size([2, 7680, 3]) torch.Size([2, 870, 3])
Hausdorff Distance is: torch.Size([2, 256, 29])


In [22]:
import torch
import numpy as np

# 假设输入张量的形状为 (B, N, 2, 3)
B = 1  # 批量大小
N = 2  # 线段数量
num_samples = 30  # 采样点数

# 随机生成输入张量
input_tensor = torch.rand(B, N, 2, 3)
# input_tensor[0,1,:,:] = input_tensor[0,0,:,:] + 0.05
# 提取起点和终点
start_points = input_tensor[:, :, 0, :]  # 形状为 (B, N, 3)
end_points = input_tensor[:, :, 1, :]    # 形状为 (B, N, 3)

# 生成等间隔的采样权重
weights = torch.linspace(0, 1, num_samples, device=input_tensor.device).view(1, 1, num_samples, 1)

# 插值计算采样点
sampled_points = start_points.unsqueeze(2) + weights * (end_points.unsqueeze(2) - start_points.unsqueeze(2))

print(sampled_points.shape)  # 输出采样点的形状 (B, N, num_samples, 3)
points = sampled_points.to(torch.float32).numpy()
print(points.shape)
# print(points[0,0,:,:])
# np.savetxt(r'C:\Users\shangfeng\Desktop\line1.txt', points[0,0,:,:])
# np.savetxt(r'C:\Users\shangfeng\Desktop\line2.txt', points[0,1,:,:])

torch.Size([1, 2, 30, 3])
(1, 2, 30, 3)


In [23]:
def torch2D_Hausdorff_distance(x,y): # Input be like (Batch,width,height)
    distance_matrix = torch.cdist(x,y,p=2) # p=2 means Euclidean Distance
    distance_matrix = distance_matrix.view(1, 1, 1, 30, -1) # B, N, M, 30, 30
    print(distance_matrix.shape)

    value1 = distance_matrix.min(-1)[0].max(-1, keepdim=True)[0]
    value2 = distance_matrix.min(-2)[0].max(-1, keepdim=True)[0]
    print(value1.shape)
    print(value2.shape)

    value = torch.cat((value1, value2), dim=-1)

    return value.max(-1, keepdim=True)[0]

if __name__ == "__main__":
    u = sampled_points[:,0,:,:]
    u = u.unsqueeze(1)
    v = sampled_points[:, 1, :, :]
    v = v.unsqueeze(1)
    print("Input shape is (B,W,H):", u.shape, v.shape)
    HD = torch2D_Hausdorff_distance(u,v)
    print("Hausdorff Distance is:", HD)

Input shape is (B,W,H): torch.Size([1, 1, 30, 3]) torch.Size([1, 1, 30, 3])
torch.Size([1, 1, 1, 30, 30])
torch.Size([1, 1, 1, 1])
torch.Size([1, 1, 1, 1])
Hausdorff Distance is: tensor([[[[0.6274]]]])


In [49]:
import torch

# 假设有两个批次，每个批次包含两个向量
batch_size = 2
vector_dim = 3

# 随机生成示例输入张量
input_tensor = torch.rand(batch_size, 2, 2, vector_dim)

# 提取每个批次的向量 A 和 B
A = input_tensor[:, 0, :]  # 第一个向量
B = -input_tensor[:, 1, :]  # 第二个向量
print(A.shape)

# 计算余弦相似度
dot_product = torch.sum(A * B, dim=1)  # 批次内的点积
norm_A = torch.norm(A, dim=1)  # 批次内的范数
norm_B = torch.norm(B, dim=1)  # 批次内的范数

cosine_similarity = abs(dot_product / (norm_A * norm_B))

print(1-cosine_similarity)

torch.Size([2, 3])
tensor([0.6087, 0.3658])


In [50]:
A = A.unsqueeze(1)
B = B.unsqueeze(1)
norm_A = torch.norm(A, dim=2, keepdim=True)  # (B, N, 1)
norm_B = torch.norm(B, dim=2, keepdim=True)  # (B, M, 1)
print(A.shape)
# 计算余弦相似度
# 首先计算所有向量的范数
# norms = torch.norm(input_tensor, dim=2, keepdim=True)  # 沿着最后一个维度计算范数
# 然后计算点积
dot_products = torch.einsum('bni,bmi->bnm', A, B)
# 最后计算余弦相似度
cosine_similarity = abs(dot_products / (norm_A * norm_B.permute(0, 2, 1)))

print(1-cosine_similarity)  # 输出余弦相似度的形状 (batch_size, num_vectors, num_vectors)

torch.Size([2, 1, 3])
tensor([[[0.6087]],

        [[0.3658]]])


In [9]:
import torch

# 假设有张量A和B，维度为 (B, N, 3) 和 (B, M, 3)
B, N, M = 2, 3, 4
A = torch.randn(B, N, 3)
B = torch.randn(B, M, 3)

# 计算余弦相似性
# 计算A和B的范数
norm_A = torch.norm(A, dim=2, keepdim=True)  # (B, N, 1)
norm_B = torch.norm(B, dim=2, keepdim=True)  # (B, M, 1)

# 计算点积
dot_product = torch.matmul(A, B.permute(0, 2, 1))  # (B, N, M)

# 计算余弦相似性
cosine_similarity = dot_product / (norm_A * norm_B.permute(0, 2, 1))  # (B, N, M)

print(cosine_similarity.shape)  # 输出余弦相似性的形状 (B, N, M)

torch.Size([2, 3, 4])


In [10]:
import torch

# 假设有张量 A 和 B，分别具有形状 (B, N, 3) 和 (B, M, 3)
B = 2  # 批量大小
N = 3  # 张量 A 中的线段数量
M = 4  # 张量 B 中的线段数量
vector_dim = 3  # 向量维度

# 随机生成示例数据（用于演示）
A = torch.randn(B, N, vector_dim)
B = torch.randn(B, M, vector_dim)

# 归一化向量
A_normalized = torch.nn.functional.normalize(A, dim=2, p=2)
B_normalized = torch.nn.functional.normalize(B, dim=2, p=2)

# 计算余弦相似度
# 使用矩阵乘法扩展到所有组合
cosine_similarity = torch.matmul(A_normalized.unsqueeze(2), B_normalized.unsqueeze(1))


RuntimeError: Expected batch2_sizes[0] == bs && batch2_sizes[1] == contraction_size to be true, but got false.  (Could this error message be improved?  If so, please report an enhancement request to PyTorch.)

In [11]:
import torch

# 示例数据
A = torch.tensor([[1.0, 1.0, 1.0], [1.0, 1.0, 1.0]])

# 归一化到单位长度（使用L2范数）
A_normalized_l2 = torch.nn.functional.normalize(A, dim=1, p=2)
print(A_normalized_l2)

# 归一化到单位长度（使用L1范数）
A_normalized_l1 = torch.nn.functional.normalize(A, dim=1, p=1)
print(A_normalized_l1)

tensor([[0.5774, 0.5774, 0.5774],
        [0.5774, 0.5774, 0.5774]])
tensor([[0.3333, 0.3333, 0.3333],
        [0.3333, 0.3333, 0.3333]])


In [41]:
import torch

# 假设张量 A 具有形状 B*N*20*3
# 假设张量 B 具有形状 B*M*20*3
B = 2  # 批量大小
N = 3  # N 维度大小
M = 4  # M 维度大小
vector_dim = 3  # 向量维度

# 创建示例张量 A 和 B
A = torch.randn(B, N, 5, vector_dim)
B1 = torch.randn(B, M, 5, vector_dim)

C = A[:, 0, :, :]
D = B1[:, 0, :, :]
print(C.shape, D.shape)
print(torch.cdist(C, D, p=2))
# 将张量 A 和 B 展平为形状为 (B*N*20, 3) 和 (B*M*20, 3) 的张量
A_flat = A.view(2, -1, 3)
B_flat = B1.view(2, -1, 3)

# 使用 torch.cdist 计算距离（例如欧几里得距离）
# p 参数为 2 表示欧几里得距离
distances = torch.cdist(A_flat, B_flat, p=2)

print(distances.view(2, 3, 5, 4, 5).transpose(2, 3)[:,0,0,:,:])  # 输出距离张量的形状 (B*N*20, B*M*20)

torch.Size([2, 5, 3]) torch.Size([2, 5, 3])
tensor([[[2.3898, 2.4138, 0.8050, 3.8793, 2.9558],
         [2.4292, 0.9984, 3.0394, 1.3057, 1.2865],
         [1.7631, 1.5905, 1.5212, 2.8727, 2.4993],
         [1.6842, 2.2480, 2.7217, 3.0582, 3.3788],
         [1.3688, 2.7979, 3.8400, 3.4825, 3.6855]],

        [[3.6133, 1.4335, 1.1342, 0.6100, 2.5234],
         [3.7264, 4.0614, 4.5351, 4.7194, 3.3268],
         [0.7689, 2.1716, 2.4532, 3.4262, 1.9457],
         [1.4715, 1.2789, 1.5387, 2.6069, 1.5580],
         [3.5846, 1.7368, 1.6570, 1.2015, 2.4930]]])
tensor([[[2.3898, 2.4138, 0.8050, 3.8793, 2.9558],
         [2.4292, 0.9984, 3.0394, 1.3057, 1.2865],
         [1.7631, 1.5905, 1.5212, 2.8727, 2.4993],
         [1.6842, 2.2480, 2.7217, 3.0582, 3.3788],
         [1.3688, 2.7979, 3.8400, 3.4825, 3.6855]],

        [[3.6133, 1.4335, 1.1342, 0.6100, 2.5234],
         [3.7264, 4.0614, 4.5351, 4.7194, 3.3268],
         [0.7689, 2.1716, 2.4532, 3.4262, 1.9457],
         [1.4715, 1.2789, 1.5387

In [51]:
import torch

def cosine_similarity_between_segments(segments1, segments2):
    """
    计算两组线段之间的余弦相似度

    参数:
    segments1 (torch.Tensor): 形状为 (B, N, 2, 3) 的张量，表示第一组线段的两个端点
    segments2 (torch.Tensor): 形状为 (B, M, 2, 3) 的张量，表示第二组线段的两个端点

    返回:
    similarity (torch.Tensor): 形状为 (B, N, M) 的张量，表示每对线段之间的余弦相似度
    """
    B, N, _, _ = segments1.shape
    _, M, _, _ = segments2.shape

    # 提取每个线段的两个端点
    start1 = segments1[:, :, 0, :]  # 形状为 (B, N, 3)
    end1 = segments1[:, :, 1, :]

    start2 = segments2[:, :, 0, :]  # 形状为 (B, M, 3)
    end2 = segments2[:, :, 1, :]

    # 计算第一组线段的方向向量
    direction1 = end1 - start1  # 形状为 (B, N, 3)

    # 计算第二组线段的方向向量
    direction2 = end2 - start2  # 形状为 (B, M, 3)

    # 归一化方向向量
    direction1_norm = torch.nn.functional.normalize(direction1, dim=2)
    direction2_norm = torch.nn.functional.normalize(direction2, dim=2)

    # 计算余弦相似度矩阵
    similarity = torch.bmm(direction1_norm, direction2_norm.permute(0, 2, 1))  # 形状为 (B, N, M)

    return similarity

# 示例用法
B = 2  # 批量大小
N = 3  # 第一组线段数量
M = 4  # 第二组线段数量
segments1 = torch.randn(B, N, 2, 3)
segments2 = torch.randn(B, M, 2, 3)

similarity = cosine_similarity_between_segments(segments1, segments2)
print(similarity.shape)  # 输出余弦相似度矩阵的形状

torch.Size([2, 3, 4])


In [1]:
import torch

def cosine_similarity_between_segments(segments1, segments2):
    """
    计算两组线段之间的余弦相似度

    参数:
    segments1 (torch.Tensor): 形状为 (B, N, 2, 3) 的张量，表示第一组线段的两个端点
    segments2 (torch.Tensor): 形状为 (B, M, 2, 3) 的张量，表示第二组线段的两个端点

    返回:
    similarity (torch.Tensor): 形状为 (B, N, M) 的张量，表示每对线段之间的余弦相似度
    """
    # 提取每个线段的两个端点
    start1 = segments1[:, :, 0, :]  # 形状为 (B, N, 3)
    end1 = segments1[:, :, 1, :]    # 形状为 (B, N, 3)

    start2 = segments2[:, :, 0, :]  # 形状为 (B, M, 3)
    end2 = segments2[:, :, 1, :]    # 形状为 (B, M, 3)

    # 计算第一组线段的方向向量
    direction1 = end1 - start1  # 形状为 (B, N, 3)

    # 计算第二组线段的方向向量
    direction2 = end2 - start2  # 形状为 (B, M, 3)

    # 计算余弦相似度
    dot_product = torch.einsum('bni,bmi->bnm', direction1, direction2)  # 形状为 (B, N, M)
    norm1 = torch.norm(direction1, dim=-1)  # 形状为 (B, N)
    norm2 = torch.norm(direction2, dim=-1)  # 形状为 (B, M)

    # 防止除零错误
    epsilon = 1e-6
    norm1 = torch.where(norm1 < epsilon, epsilon, norm1)
    norm2 = torch.where(norm2 < epsilon, epsilon, norm2)

    similarity = dot_product / (norm1.unsqueeze(2) * norm2.unsqueeze(1))  # 形状为 (B, N, M)

    return similarity

# 示例用法
B = 2  # 批量大小
N = 3  # 第一组线段数量
M = 4  # 第二组线段数量
segments1 = torch.randn(B, N, 2, 3)
segments2 = torch.randn(B, M, 2, 3)

similarity = cosine_similarity_between_segments(segments1, segments2)
print(similarity.shape)  # 输出余弦相似度矩阵的形状

RuntimeError: expected scalar type double but found float

In [3]:
import torch

# 创建一个示例输入张量
input = torch.tensor([[1, 2, 3],
                      [4, 5, 6],
                      [7, 8, 9]])

# 创建一个索引张量，指定要在第 1 维度上收集的索引
index = torch.tensor([[0],
                      [2],
                      [1]])

# 使用 torch.gather 从 input 中收集指定位置的值
output = torch.gather(input, 1, index)

print(output)

tensor([[1],
        [6],
        [8]])


In [10]:
# Example of target with class indices
import torch.nn.functional as F
input = torch.randn(3, 5, requires_grad=True)
target = torch.randint(5, (3,), dtype=torch.int64)
loss = F.cross_entropy(input, target)
print(loss)
print(input)
print(target)
# >>> loss.backward()
# >>> # Example of target with class probabilities
input = torch.randn(3, 5, requires_grad=True)
target = torch.randn(3, 5).softmax(dim=1)
# >>> loss = F.cross_entropy(input, target)
# >>> loss.backward()
print(input)
print(target)

tensor(2.4806, grad_fn=<NllLossBackward0>)
tensor([[ 0.4550,  0.5073, -0.2978,  2.3917,  0.5695],
        [ 0.4003,  0.1979,  0.5506, -0.8764, -0.6519],
        [ 0.2486, -1.1681, -0.6212, -0.1841, -1.6479]], requires_grad=True)
tensor([2, 3, 2])
tensor([[-0.0399, -1.2654,  1.0844,  0.5724, -0.7414],
        [ 0.1755,  0.8239, -1.5127, -0.6490, -0.4658],
        [-1.0944, -1.6821, -1.1379,  0.4537, -1.5439]], requires_grad=True)
tensor([[0.4945, 0.0937, 0.1502, 0.0988, 0.1628],
        [0.2132, 0.1725, 0.1446, 0.2531, 0.2166],
        [0.2461, 0.1893, 0.0986, 0.4154, 0.0506]])


In [12]:
input = torch.randn((3, 2), requires_grad=True)
target = torch.rand((3, 2), requires_grad=False)
loss = F.binary_cross_entropy(F.sigmoid(input), target)
print(input)
print(target)
# >>> loss.backward()

tensor([[-0.6943, -1.8080],
        [-1.6374,  1.9197],
        [-2.6542,  0.5151]], requires_grad=True)
tensor([[0.6340, 0.8597],
        [0.4793, 0.4414],
        [0.7615, 0.5990]])


/opt/conda/lib/python3.7/site-packages/torch/nn/functional.py:1806: UserWarning: nn.functional.sigmoid is deprecated. Use torch.sigmoid instead.
  warnings.warn("nn.functional.sigmoid is deprecated. Use torch.sigmoid instead.")


In [60]:
import torch
import torch.nn.functional as F

# # 创建示例预测和目标标签
# predictions = torch.tensor([0.8, 0.2, 0.6, 0.3])  # 模型的预测概率值（sigmoid 函数的输出）
# targets = torch.tensor([1, 0, 0, 0], dtype=torch.float32)  # 真实标签，1 表示前景，0 表示背景
predictions = torch.rand(2, 256)  # 模型的预测概率值（sigmoid 函数的输出）
targets = torch.zeros(2, 256)  # 真实标签，1 表示前景，0 表示背景
indices = torch.randperm(256)[:17]
targets[0, indices] = 1
weights = torch.ones(1, 2) * 0.2
weights[0, indices] = 1

# 使用 F.binary_cross_entropy 计算二元交叉熵损失
loss = F.binary_cross_entropy(predictions, targets, weights,reduction="mean")

print(loss)
print(F.binary_cross_entropy(predictions, targets))

RuntimeError: The size of tensor a (256) must match the size of tensor b (2) at non-singleton dimension 1

In [59]:
def FocalLoss(predictions, targets, alpha, gamma):
    # 计算二元交叉熵损失
    bce_loss = F.binary_cross_entropy(predictions, targets, reduction='none')

    # 计算预测概率值
    p_t = torch.exp(-bce_loss)

    # 计算 Focal Loss
    focal_loss = alpha * (1 - p_t)**gamma * bce_loss

    return focal_loss.mean()


import torch
import torch.nn.functional as F

# 创建示例预测和目标标签
# predictions = torch.rand(1, 256)  # 模型的预测概率值（sigmoid 函数的输出）
# targets = torch.zeros(1, 100)  # 真实标签，1 表示前景，0 表示背景
# indices = torch.randperm(100)[:2]
# targets[0, indices] = 1
# 定义 Focal Loss 的参数
alpha = 0.25  # 正样本的权重
gamma = 2.0   # 调整因子

# 使用 Focal Loss 计算损失
loss = FocalLoss(predictions, targets, alpha, gamma)

print(loss)


tensor(0.1730)


In [73]:
import torch
import torch.nn.functional as F

# 示例数据
B = 32  # 批量大小
N = 100  # 样本数量
# 随机生成模拟的预测值 logits 和相应的标签 targets
logits = torch.randn(B, N)
print(logits.shape)
targets = torch.randint(0, 2, (B, N), dtype=torch.float32)  # 随机生成二分类标签
print(targets)

# 计算损失
# 将正样本的权重设置为1，负样本的权重设置为0.2
weights = torch.where(targets == 1, torch.tensor(1.0), torch.tensor(0.2))
loss = F.binary_cross_entropy_with_logits(logits, targets, weight=weights, reduction='mean')

print("Weighted Binary Cross-Entropy Loss:", loss.item())


torch.Size([32, 100])
tensor([[1., 1., 1.,  ..., 0., 0., 0.],
        [0., 0., 0.,  ..., 0., 0., 0.],
        [0., 1., 1.,  ..., 1., 0., 0.],
        ...,
        [1., 0., 1.,  ..., 1., 0., 0.],
        [0., 1., 0.,  ..., 1., 0., 1.],
        [0., 0., 1.,  ..., 1., 0., 1.]])
Weighted Binary Cross-Entropy Loss: 0.4759114384651184


In [1]:
test = {}
print(test.keys())

dict_keys([])


In [2]:
test['qwe'] = (20*100)

In [3]:
print(test)

{'qwe': 2000}


In [5]:
print(f"Metrics {test}")

Metrics {'qwe': 2000}


In [15]:
import sys
sys.path.append('utils')
from ap_calculator import APCalculator
class2type = {0: "cabinet",
            1: "bed",
            2: "chair"}
ap_calculator = APCalculator(
        dataset_config={},
        ap_iou_thresh=[0.25, 0.5],
        class2type_map=class2type,
        exact_eval=False,
    )

ModuleNotFoundError: No module named 'ap_calculator'

In [3]:
import numpy as np

# 示例输入数组
input_array = np.array([[[1, 2, 3], [4, 5, 6]],
                        [[1, 2, 3], [7, 8, 9]],
                        [[4, 5, 6], [1, 2, 3]],
                        [[7, 8, 9], [1, 2, 3]]])

# 将输入数组展平成形状为 (n*2, 3) 的二维数组
flattened_array = input_array.reshape(-1, 3)
print(flattened_array.shape)

# 使用 np.unique 去除重复的行
unique_rows = np.unique(flattened_array, axis=0)

# 将结果重新组织成形状为 (n, 2, 3) 的数组
result_array = unique_rows

print(result_array)

(8, 3)
[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [60]:
from sklearn.cluster import DBSCAN
import numpy as np

# 创建示例数据集
np.random.seed(4)
n_samples = 300
data = np.random.rand(n_samples, 3) * 2 - 1

# 创建DBSCAN模型并设置参数
eps = 0.3
min_samples = 2
dbscan = DBSCAN(eps=eps, min_samples=min_samples)

# 拟合数据并获取聚类标签
labels = dbscan.fit_predict(data)
print(set(labels))
index = labels.reshape(300, 1)
# print(index.type)

# 计算每个簇的中心点
unique_labels = set(labels) - {-1}  # 去除噪声点的标签
cluster_centers = []
# print(unique_labels.dtype)

for label in unique_labels:
    cluster_mask = (labels == label)
    if sum(cluster_mask) > 3:
        print(True)
    cluster_data = data[cluster_mask]
    cluster_center = np.mean(cluster_data, axis=0)
    cluster_centers.append(cluster_center)

print(len(cluster_centers))
# 输出每个簇的中心点
# for i, center in enumerate(cluster_centers):
#
#     print(f"Cluster {i+1} Center:", center)

{0, 1, 2, 3, 4, 5, 6, 7, -1}


AttributeError: 'numpy.ndarray' object has no attribute 'type'

In [64]:
import numpy as np

# 创建示例数组
arr = np.array([[1, 9],
                [3, 4],
                [-1, 6],
                [7, 8]])

# 找到包含 -1 的行的索引
rows_to_delete = np.any(arr == -1, axis=1)

# 删除包含 -1 的行
filtered_arr = arr[~rows_to_delete]
print(rows_to_delete)
# 输出删除后的数组
print(filtered_arr)
# print(set(arr))

[False False  True False]
[[1 9]
 [3 4]
 [7 8]]


In [63]:
def fu(a, b):
    a = b
    return 0

a = 1
b=3
fu(a, b)
print(a, b)

1 3


In [66]:
import numpy as np

# 创建一个空的数组（形状为 (0, 3) 的空数组，表示0行3列）
empty_array = np.empty((0, 3))

# 创建其他数组
array1 = np.array([[1, 2, 3]])
array2 = np.array([[4, 5, 6]])

# 拼接数组1到空数组
empty_array = np.concatenate((empty_array, array1), axis=0)

# 拼接数组2到空数组
empty_array = np.concatenate((empty_array, array2), axis=0)

# empty_array 现在包含了数组1和数组2的内容
print(empty_array)


[[1. 2. 3.]
 [4. 5. 6.]]


In [2]:
import numpy as np

# 示例数组 A 和 B
A = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
B = np.array([[[1, 2, 3], [4, 5, 6]], [[1, 2, 3], [7, 8, 9]], [[4, 5, 6], [7, 8, 9]]])

# 创建一个空列表来存储匹配的索引对
matches = []

# 遍历数组 B 中的元素，查找与数组 A 中的元素匹配的索引对
for i, b_pair in enumerate(B):
    for j, a in enumerate(A):
        if np.array_equal(b_pair[0], a) or np.array_equal(b_pair[1], a):
            matches.append((i, j))

# 打印匹配的索引对
for match in matches:
    print("B[{}] 匹配到 A[{}]".format(match[0], match[1]))

IndexError: index 0 is out of bounds for axis 0 with size 0

In [3]:
import numpy as np

# 假设 label_edges 和 l_corners 的示例数据如下，你需要替换成你的实际数据
label_edges = np.array([[[1, 2, 3], [4, 5, 6]],
                        [[4, 5, 6], [7, 8, 9]],
                        [[7, 8, 9], [1, 2, 3]]])

all_vertices = label_edges.reshape(-1, 3)
l_corners = np.unique(all_vertices, axis=0)

# 创建一个空的 label_index 数组，用于保存结果
label_index = []

# 遍历 label_edges 中的每个元素
for edge in label_edges:
    indices = []
    for point in edge:
        # 使用 np.where 查找匹配的位置并返回索引
        matching_indices = np.where((l_corners == point).all(axis=1))[0]
        if len(matching_indices) > 0:
            indices.append(matching_indices[0])
        else:
            indices.append(-1)  # 如果没有匹配的点，可以使用 -1 表示

    label_index.append(indices)

# 将 label_index 转换为 NumPy 数组
label_index = np.array(label_index)

# 打印 label_index
print(label_index)

[[0 1]
 [1 2]
 [2 0]]


In [10]:
import numpy as np

# 假设n*2的数组示例数据如下，你需要替换成你的实际数据
data = np.array([[3, 1],
                 [2, 4],
                 [5, 2],
                 [1, 6]])

# 使用 numpy.sort 对每一组进行排序
sorted_data = np.sort(data, axis=1)

# 打印排序后的数组
print(sorted_data)


[[1 3]
 [2 4]
 [2 5]
 [1 6]]


In [1]:
from collections import OrderedDict
z = OrderedDict()
z['test'] += 1

KeyError: 'test'

In [19]:
# strs = 'as'
import numpy as np
a = np.array(0.05)
print('%s_all_average_corner_offset: ' % (a))

0.05_all_average_corner_offset: 


In [26]:
a = str(0.2)
print('-------------------------- ' + a + ' ------------------------------')

TypeError: 'str' object is not callable

In [11]:
import os
import numpy as np
data_dir = '/workspace/WFTR/data/Entry-level/train_1/xyz'
out_dir = '/workspace/WFTR/data/Entry-level/train/xyz'
for file in os.listdir(data_dir):
    out_file = os.path.join(out_dir, file)
    xyz_file = os.path.join(data_dir, file)
    xyz = np.loadtxt(xyz_file, dtype=np.float64)
    if not xyz[0,7] < 100:
        xyz[:, 7] = xyz[:, 7] / 65536.0
    else:
        print(xyz_file)
    np.savetxt(out_file, xyz, fmt='%f')

/workspace/WFTR/data/Entry-level/train_1/xyz/3.xyz
/workspace/WFTR/data/Entry-level/train_1/xyz/2.xyz


In [12]:
import os
import numpy as np
data_dir = '/workspace/WFTR/data/Entry-level/test_1/xyz'
out_dir = '/workspace/WFTR/data/Entry-level/test/xyz'
for file in os.listdir(data_dir):
    out_file = os.path.join(out_dir, file)
    xyz_file = os.path.join(data_dir, file)
    xyz = np.loadtxt(xyz_file, dtype=np.float64)
    if not xyz[0,7] < 100:
        xyz[:, 7] = xyz[:, 7] / 65536.0
    else:
        print(xyz_file)
    np.savetxt(out_file, xyz, fmt='%f')

In [19]:
import torch
import torch.nn.functional as F
input = torch.randn(3, requires_grad=True)
target = torch.randn(3, requires_grad=False)
loss = F.binary_cross_entropy_with_logits(input, target)
print(target)
print(loss)

tensor([ 0.5767,  1.9179, -0.1612])
tensor(1.7155, grad_fn=<BinaryCrossEntropyWithLogitsBackward>)


In [20]:
# input = torch.randn((3, 2), requires_grad=True)
# target = torch.rand((3, 2), requires_grad=False)
loss = F.binary_cross_entropy(F.sigmoid(input), target)
print(target)
print(loss)

tensor([ 0.5767,  1.9179, -0.1612])
tensor(1.7155, grad_fn=<BinaryCrossEntropyBackward>)
